server:
  port: 30081

spring:
  application:
    name: IMAGE-SERVICE
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    password: 123456
    url: jdbc:mysql://4.196.159.180:8036/piczio
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
##    config:
##        import:
##            optional:
##                configserver: http://localhost:30888
#

minio:
  url: http://http://4.196.159.180:32768/
  access-key: k9lMPwsWdLpWiRxGwG7O
  secret-key: iWLYjk1iVJUY3UTRj5jqSnDJJmaIxtEon9BbHxia
  bucket-name: picizoimages

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30761/eureka/

