spring:
    datasource:
        password: 123456
        url: jdbc:mysql://4.196.159.180:3306/piczio_user
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
