server:
    port: 30080

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 1063640680585-4m7673brd1p2fsjfuep7vatg7cb1etdo.apps.googleusercontent.com
                        client-secret: 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
    application:
        name: USER-SERVICE
    datasource:
        password: 123456
        url: jdbc:mysql://4.196.159.180:8036/piczio
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:30761/eureka/


application:
    security:
        jwt:
            secret-key: NYn0qAcyxkZRAfs7F55St/BD7+ovlQhRKPxKUqT8ZRE=
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days

management:
    endpoints:
        web:
            exposure:
                include: "*"

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        path: /swagger-ui
