server:
  port: 30191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: management
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/management/**

        - id: authenticate
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: image
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/api/v1/images/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30761/eureka/
