server:
  port: 30888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tungdapoet/piczio-config-server.git
          clone-on-start: true
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:30761/eureka/

